import type { Barber } from './scoring';
export type VisualToken={text:string;x:number;y:number;w:number;h:number;cls?:string;tag?:string;title?:string;aria?:string};
export type MeevoBridgeSnapshot={at:string;url:string;title:string;visibleText:string;visualTokens?:VisualToken[]};
const clean=(s:string)=>s.replace(/\s+/g,' ').trim();
const num=(s:string)=>Number((s.match(/-?[\d,.]+/)?.[0]||'0').replace(/,/g,''));
const rejectHeader=/(meevo|home|appointment|register|today|go|off|lunch|chair|default|smart center|client|service|checkout|calendar|book|more information)/i;
const headerName=(s:string)=>/^[A-Za-zÀ-ÿ][A-Za-zÀ-ÿ' .-]{1,30}$/.test(s)&&!rejectHeader.test(s);
const service=/(signature cut|fade cut|hot lather|beard trim|haircut|shave|color|facial|permed|express facial|cut)/i;
const center=(t:VisualToken)=>t.x+t.w/2;
function bestPercentRow(ts:VisualToken[]){const perc=ts.filter(t=>/^\d{1,3}\s*%$/.test(clean(t.text))&&num(t.text)<=100);if(!perc.length)return[];const rows:VisualToken[][]=[];for(const p of perc.sort((a,b)=>a.y-b.y)){let row=rows.find(r=>Math.abs(r[0].y-p.y)<=18);if(!row){row=[];rows.push(row)}row.push(p)}return rows.sort((a,b)=>b.length-a.length)[0]||[]}
function parseAppointmentBook(snapshot:MeevoBridgeSnapshot):Barber[]{const ts=snapshot.visualTokens||[];const headerPerc=bestPercentRow(ts).sort((a,b)=>center(a)-center(b));if(!headerPerc.length)return[];const headerY=headerPerc.reduce((s,p)=>s+p.y,0)/headerPerc.length;
 const allNames=ts.filter(t=>headerName(clean(t.text))&&t.y>=headerY-90&&t.y<=headerY+100);
 const anchors:Array<{name:VisualToken,percent:VisualToken}>=[];for(const p of headerPerc){const pc=center(p);const matches=allNames.map(n=>({n,dx:Math.abs(center(n)-pc),dy:Math.abs(n.y-p.y)})).filter(v=>v.dx<120).sort((a,b)=>(a.dx*5+a.dy)-(b.dx*5+b.dy));const n=matches[0]?.n;if(n&&!anchors.some(a=>clean(a.name.text).toUpperCase()===clean(n.text).toUpperCase()))anchors.push({name:n,percent:p})}
 // Fallback for Meevo variants where the percentage is embedded in the same header node as the barber name.
 if(!anchors.length){for(const t of ts.filter(t=>t.y>=headerY-100&&t.y<=headerY+100)){const text=clean(t.text),m=text.match(/^([A-Za-zÀ-ÿ][A-Za-zÀ-ÿ' .-]{1,30})\s+(\d{1,3})\s*%$/);if(m&&headerName(m[1]))anchors.push({name:{...t,text:m[1]},percent:{...t,text:`${m[2]}%`}})}}
 anchors.sort((a,b)=>center(a.percent)-center(b.percent));if(!anchors.length)return[];
 return anchors.map(({name:n,percent:p},i)=>{const c=center(p),prev=i?center(anchors[i-1].percent):null,next=i<anchors.length-1?center(anchors[i+1].percent):null,left=prev==null?c-(next!=null?(next-c)/2:90):(prev+c)/2,right=next==null?c+(prev!=null?(c-prev)/2:90):(c+next)/2;const column=ts.filter(t=>{const tc=center(t);return tc>=left&&tc<right&&t.y>headerY+35});const texts=column.map(t=>clean(t.text)).filter(Boolean);const joined=texts.join(' | ');const off=texts.some(x=>/^(OFF|OFF SHIFT|NOT WORKING)$/i.test(x));const lunch=texts.some(x=>/^(LUNCH|BREAK)$/i.test(x));const serviceTokens=column.filter(t=>service.test(clean(t.text)));const cardYs:number[]=[];for(const t of serviceTokens.sort((a,b)=>a.y-b.y)){if(!cardYs.some(y=>Math.abs(y-t.y)<32))cardYs.push(t.y)}const name=clean(n.text).toLowerCase().replace(/(^|\s)\S/g,s=>s.toUpperCase());return{id:10000+i,externalId:`bridge:${name.toUpperCase()}`,name,status:off?'OFF SHIFT':lunch?'BREAK':'AVAILABLE',appointments:cardYs.length,occupancy:num(p.text),revenue:0,completed:0,walkins:0,idle:0,next:0,rejections:0,breakMinutes:lunch?1:0,scheduledToday:!off};});}
function parseOne(s:MeevoBridgeSnapshot){const text=`${s.title} ${s.url} ${s.visibleText.slice(0,2000)}`;return /appointment|calendar|book/i.test(text)?parseAppointmentBook(s):parseAppointmentBook(s)}
export function parseBridgeSnapshots(snapshots:MeevoBridgeSnapshot[]):Barber[]{const latest=[...snapshots].sort((a,b)=>Date.parse(b.at)-Date.parse(a.at));for(const s of latest){const parsed=parseOne(s);if(parsed.length)return parsed}return[]}
export function listenForMeevoBridge(onSnapshot:(snapshot:MeevoBridgeSnapshot,barbers:Barber[])=>void){const handler=(event:MessageEvent)=>{if(event.origin!==location.origin||event.data?.source!=='NEXT_WALKING_MEEVO_BRIDGE')return;if(event.data?.type==='MEEVO_SNAPSHOTS'){const snapshots=event.data.payload as MeevoBridgeSnapshot[];if(snapshots?.length){const latest=[...snapshots].sort((a,b)=>Date.parse(b.at)-Date.parse(a.at))[0];onSnapshot(latest,parseBridgeSnapshots(snapshots))}}};window.addEventListener('message',handler);window.postMessage({source:'NEXT_WALKING_APP',type:'BRIDGE_READY'},location.origin);return()=>window.removeEventListener('message',handler)}