import type { Barber } from './scoring';
export type VisualToken={text:string;x:number;y:number;w:number;h:number;cls?:string;tag?:string;title?:string;aria?:string};
export type MeevoBridgeSnapshot={at:string;url:string;title:string;visibleText:string;visualTokens?:VisualToken[]};
const clean=(s:string)=>s.replace(/\s+/g,' ').trim();
const blocked=new Set(['MEEVO','HOME','APPOINTMENT BOOK','REGISTER','TODAY','GO','LUNCH','OFF','CHAIR','DEFAULT','APPOINTMENTS','CLIENTS','SERVICES','SERVICE','REVENUE','TOTAL','AVAILABLE','MORE INFORMATION','FORGOT YOUR PASSWORD','ACCESS','BEARD TRIM','PEDICURE','BEARD COLOR','LOGIN','SIGN IN','PASSWORD','USERNAME','CATEGORY','LIVE','RANKING']);
const noise=/(password|information|access|pedicure|beard|service|appointment|register|login|sign in|category|client|forgot)/i;
const isName=(s:string)=>/^[A-Za-z' -]{2,30}$/.test(s)&&!blocked.has(s.toUpperCase())&&!noise.test(s);
const num=(s:string)=>Number((s.match(/-?[\d,.]+/)?.[0]||'0').replace(/,/g,''));
const statusOf=(s:string):Barber['status']=>{const u=s.toUpperCase();if(/OFF SHIFT|NOT WORKING/.test(u))return'OFF SHIFT';if(/BREAK|LUNCH/.test(u))return'BREAK';if(/WITH CLIENT|IN SERVICE|CHECKED IN|IN PROGRESS/.test(u))return'WITH CLIENT';if(/APPOINTMENT SOON|UPCOMING/.test(u))return'APPOINTMENT SOON';return'AVAILABLE'};
function parseOne(snapshot:MeevoBridgeSnapshot):Barber[]{const ts=snapshot.visualTokens||[];const names=ts.filter(t=>isName(clean(t.text)));const perc=ts.filter(t=>/^\d{1,3}%$/.test(clean(t.text))&&num(t.text)<=100);const anchors=new Map<string,{name:VisualToken;percent:VisualToken}>();for(const p of perc){const pc=p.x+p.w/2;const candidate=names.map(n=>({n,dx:Math.abs((n.x+n.w/2)-pc),dy:p.y-n.y})).filter(v=>v.dy>=0&&v.dy<=180&&v.dx<90).sort((a,b)=>(a.dx*3+a.dy)-(b.dx*3+b.dy))[0]?.n;if(candidate)anchors.set(clean(candidate.text).toUpperCase(),{name:candidate,percent:p})}if(!anchors.size)return[];return[...anchors.entries()].map(([raw,{name:a,percent:p}],i)=>{const center=a.x+a.w/2;const local=ts.filter(t=>Math.abs((t.x+t.w/2)-center)<=110&&t.y>=Math.min(a.y,p.y)-40&&t.y<=Math.max(a.y,p.y)+320);const joined=local.map(t=>[t.text,t.title,t.aria].filter(Boolean).join(' ')).join(' | ');const occupancy=num(p.text);const money=[...joined.matchAll(/\$\s?([\d,]+(?:\.\d{1,2})?)/g)].map(m=>num(m[1]));const revenue=money.length?Math.max(...money):0;const serviceMatch=joined.match(/(?:services?|completed)\s*[:#]?\s*(\d+)/i)||joined.match(/(\d+)\s*(?:services?|completed)/i);const apptMatch=joined.match(/(?:appointments?|appts?)\s*[:#]?\s*(\d+)/i)||joined.match(/(\d+)\s*(?:appointments?|appts?)/i);const nextMatch=joined.match(/(?:next|appointment)\D{0,12}(\d{1,3})\s*min/i);const name=raw.toLowerCase().replace(/(^|\s)\S/g,s=>s.toUpperCase());return{id:10000+i,externalId:`bridge:${raw}`,name,status:statusOf(joined),appointments:apptMatch?num(apptMatch[1]):0,occupancy,revenue,completed:serviceMatch?num(serviceMatch[1]):0,walkins:0,idle:0,next:nextMatch?num(nextMatch[1]):90,rejections:0,breakMinutes:/break|lunch/i.test(joined)?1:0,scheduledToday:!(/off shift|not working/i.test(joined))};});}
export function parseBridgeSnapshots(snapshots:MeevoBridgeSnapshot[]):Barber[]{const merged=new Map<string,Barber>();for(const s of snapshots){for(const b of parseOne(s)){const k=b.name.toUpperCase(),p=merged.get(k);if(!p){merged.set(k,b);continue}merged.set(k,{...p,status:b.status!=='AVAILABLE'?b.status:p.status,appointments:Math.max(p.appointments,b.appointments),occupancy:b.occupancy||p.occupancy,revenue:Math.max(p.revenue,b.revenue),completed:Math.max(p.completed,b.completed),next:b.next!==90?b.next:p.next,breakMinutes:Math.max(p.breakMinutes||0,b.breakMinutes||0),scheduledToday:p.scheduledToday!==false&&b.scheduledToday!==false})}}return[...merged.values()].map((b,i)=>({...b,id:10000+i}))}
export function listenForMeevoBridge(onSnapshot:(snapshot:MeevoBridgeSnapshot,barbers:Barber[])=>void){const handler=(event:MessageEvent)=>{if(event.origin!==location.origin||event.data?.source!=='NEXT_WALKING_MEEVO_BRIDGE')return;if(event.data?.type==='MEEVO_SNAPSHOTS'){const snapshots=event.data.payload as MeevoBridgeSnapshot[];if(snapshots?.length){const latest=[...snapshots].sort((a,b)=>Date.parse(b.at)-Date.parse(a.at))[0];onSnapshot(latest,parseBridgeSnapshots(snapshots))}}};window.addEventListener('message',handler);return()=>window.removeEventListener('message',handler)}
